### ISSUE TITLE
removeAt(index) throws IndexOutOfBoundsException

### ISSUE THREAD

**Issue by HamidurRahman1** [Slaeh/Data-Structures#1]
loop inside removeAt(index) should go until **_`i < counter - 1;`_**

```
class Main {
  public static void main(String[] args) {
    Array a = new Array(3);
    a.insert(2); 
    a.insert(4);
    a.insert(5);
    a.removeAt(0);
  }
}
```
By running this will throw an IndexOutOfBoundsException.

Correction:

```
public void removeAt(int index) {
    if(index < 0 || index >= counter) {
        throw new IllegalArgumentException("Index not valid");
     }else {
	for(int i = index; i < counter - 1; i++) {
	    array[i] = array[i+1];
	}
	counter--;
     }
}
```

**Comment by Slaeh** [comment]
Hey, just looked at my code and you're right. Thanks for the review!

**Comment by HamidurRahman1** [comment]
Sure. I saw that you're working on DS and wanted to brush up mine and also poke around with GitHub features to get used to it. I'll close the issue now or once maybe you update the code
